CREATE SCHEMA "pawel";

CREATE SCHEMA "genre_set";

CREATE SCHEMA "rate_set";

CREATE SCHEMA "friends";

CREATE TYPE "pawel"."genre_status" AS ENUM (
  'COMEDY',
  'DRAMA',
  'CARTOON',
  'TRILLER',
  'DOCUMENTARY',
  'HITMAN',
  'INDISTINCT'
);

CREATE TYPE "pawel"."type_friend" AS ENUM (
  'FRIEND',
  'NO_FRIEND',
  'FRIEND_REQUEST'
);

CREATE TYPE "pawel"."rate_status" AS ENUM (
  'G',
  'PG',
  'PG14',
  'R',
  'NC17'
);

CREATE TABLE "pawel"."films" (
  "id_film" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar(200),
  "release_Date" timestamp,
  "duration" int8
);

CREATE TABLE "pawel"."users" (
  "id_user" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "login" varchar,
  "email" varchar,
  "birthday" timestamp,
  "name" varchar
);

CREATE TABLE "pawel"."likes_set" (
  "id" int PRIMARY KEY,
  "id_film" int,
  "id_user" int
);

CREATE TABLE "pawel"."genre_set" (
  "id" int PRIMARY KEY,
  "id_film" int,
  "id_genre" int NOT NULL
);

CREATE TABLE "pawel"."rate_set" (
  "id" int PRIMARY KEY,
  "id_film" int,
  "id_rate" int NOT NULL
);

CREATE TABLE "pawel"."friends" (
  "id" int PRIMARY KEY,
  "id_user" int,
  "id_friend" int NOT NULL,
  "id_type" int NOT NULL
);

CREATE TABLE "genre_set"."genre" (
  "id_genre" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "genre_Date" pawel.genre_status DEFAULT (INDISTINCT),
  "genre_rus" varchar
);

CREATE TABLE "rate_set"."rate" (
  "id_rate" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rate_Date" pawel.rate_status,
  "rate" varchar
);

CREATE TABLE "friends"."type_friends" (
  "id_type" int,
  "type" pawel.type_friend
);

CREATE UNIQUE INDEX ON "pawel"."friends" ("id_user", "id_friend");

COMMENT ON COLUMN "genre_set"."genre"."genre_rus" IS 'formated RUS';

COMMENT ON COLUMN "rate_set"."rate"."rate" IS 'formated МРА';

ALTER TABLE "genre_set"."genre" ADD FOREIGN KEY ("id_genre") REFERENCES "pawel"."genre_set" ("id_genre");

ALTER TABLE "rate_set"."rate" ADD FOREIGN KEY ("id_rate") REFERENCES "pawel"."rate_set" ("id_rate");

ALTER TABLE "friends"."type_friends" ADD FOREIGN KEY ("id_type") REFERENCES "pawel"."friends" ("id_type");

ALTER TABLE "pawel"."likes_set" ADD FOREIGN KEY ("id_film") REFERENCES "pawel"."films" ("id_film");

ALTER TABLE "pawel"."genre_set" ADD FOREIGN KEY ("id_film") REFERENCES "pawel"."films" ("id_film");

ALTER TABLE "pawel"."rate_set" ADD FOREIGN KEY ("id_film") REFERENCES "pawel"."films" ("id_film");

ALTER TABLE "pawel"."likes_set" ADD FOREIGN KEY ("id_user") REFERENCES "pawel"."users" ("id_user");

ALTER TABLE "pawel"."friends" ADD FOREIGN KEY ("id_user") REFERENCES "pawel"."users" ("id_user");
